/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * API version: 2.0
 * Contact: support@bitbucket.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api

type RepositoryLinks struct {
	Self *Link `json:"self,omitempty"`
	Html *Link `json:"html,omitempty"`
	Avatar *Link `json:"avatar,omitempty"`
	Pullrequests *Link `json:"pullrequests,omitempty"`
	Commits *Link `json:"commits,omitempty"`
	Forks *Link `json:"forks,omitempty"`
	Watchers *Link `json:"watchers,omitempty"`
	Downloads *Link `json:"downloads,omitempty"`
	Clone []Link `json:"clone,omitempty"`
	Hooks *Link `json:"hooks,omitempty"`
}
