/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * API version: 2.0
 * Contact: support@bitbucket.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api
import (
	"time"
)

type DeploymentStateInProgress struct {
	// The name of deployment state (IN_PROGRESS).
	Name string `json:"name,omitempty"`
	// Link to the deployment result.
	Url string `json:"url,omitempty"`
	Deployer *Account `json:"deployer,omitempty"`
	// The timestamp when the deployment was started.
	StartDate time.Time `json:"start_date,omitempty"`
}
